added version comparing function(s)

diff --git a/minecraft b/minecraft
--- a/minecraft
+++ b/minecraft
@@ -75,6 +75,37 @@ array_contains() {
   return 1
 }
 
+# Version timestamp
+version_timestamp() {
+  # Usage
+  #   version_timestamp "x.x.x"
+  #   Gives back a printf of version timestamp for comparison, eg:
+  #   [ $(version_timestamp "1.2.5") -lt $(version_timestamp "1.8") ]
+  
+  local version id_regex releasetime releasetime_regex v
+  
+  version="$1"
+  id_regex="\"id\": \"($version)\""
+  release_regex="\"releaseTime\": \"(.*)\""
+  
+  as_user "wget -qN -P $resources $versions_json"
+  
+  v="false"
+  while read line; do
+    if [[ $line =~ $id_regex ]]; then
+      v="true"
+    fi
+    if [[ $v = "true" ]]; then
+      [[ $line =~ $release_regex ]]
+      [[ ! -z ${BASH_REMATCH[1]} ]] && v="false" && releasetime="${BASH_REMATCH[1]}" && break
+    fi
+  done <"$resources/versions.json"
+  
+  printf "%s" $(date -d "$releasetime" +%s)
+  
+  return 0
+}
+
 server_command() {
   # Usage
   #   server_command "<command>"
@@ -323,16 +354,29 @@ server_reload() {
     return 1
   fi
   
-  server_command "difficulty ${server_setting[difficulty]}"
-  sleep 1
-  server_command "defaultgamemode ${server_setting[gamemode]}"
-  sleep 1
-  server_command "setidletimeout ${server_setting[player-idle-timeout]}"
-  sleep 1
-  server_command "whitelist $whitelist"
-  sleep 1
-  server_command "whitelist reload"
-  sleep 1
+  if server_version; then
+    
+    if server_version_minimum "12w32a"; then
+      server_command "difficulty ${server_setting[difficulty]}"
+      sleep 1
+    fi
+    
+    if server_version_minimum "12w22a"; then
+      server_command "defaultgamemode ${server_setting[gamemode]}"
+      sleep 1
+    fi
+    
+    if server_version_minimum "13w38a"; then
+      server_command "setidletimeout ${server_setting[player-idle-timeout]}"
+      sleep 1
+    fi
+    
+    server_command "whitelist $whitelist"
+    sleep 1
+    server_command "whitelist reload"
+    sleep 1
+    
+  fi
   
   return 0
 }
@@ -345,6 +389,8 @@ server_start() {
   
   timestamp=$(date '+%s')
   
+  [ -d "$server" ] || as_user "mkdir -p $server"
+  [ -f "$server/$jar" ] || exit 1
   cd $server || exit 1
   
   # Create fifo if it doesn't exist
@@ -456,12 +502,15 @@ server_update_check() {
   
   json_regex="\"($version)\": \"(.*)\""
   
+  as_user "mkdir -p $resources"
+  as_user "wget -qN -P $resources $versions_json"
+  
   while read line; do
     if [[ $line =~ $json_regex ]]; then
       version_online="${BASH_REMATCH[2]}"
       break
     fi
-  done <<<"$(wget -qO- $versions_json)"
+  done <"$resources/versions.json"
   
   [[ -z $version_online ]] && return 2
   
@@ -480,7 +529,6 @@ server_version() {
   # Return
   #   0 if version value is stored in $version_current
   #   1 if server $version_current could not be determined
-  #
   
   local arg=$1 line
   
@@ -496,6 +544,24 @@ server_version() {
   done <$log || return 1
   
   return 0
+}
+
+server_version_minimum() {
+  # Usage
+  #   server_version_minimum <x.x.x>
+  # Return
+  #   0 if $version_current is more than or equal to compared version x.x.x
+  #   1 if comparison failed
+  
+  if server_version; then
+    if [ "$(version_timestamp \"$version_current\")" -ge "$(version_timestamp \"$1\")" ]; then
+      return 0
+    else
+      return 1
+    fi
+  else
+    return 1
+  fi
 }
 
 case "$1" in
