added ability to set fixed version in config

diff --git a/minecraft b/minecraft
--- a/minecraft
+++ b/minecraft
@@ -88,6 +88,7 @@ version_timestamp() {
   id_regex="\"id\": \"($version)\""
   release_regex="\"releaseTime\": \"(.*)\""
   
+  as_user "mkdir -p $resources"
   as_user "wget -qN -P $resources $versions_json"
   
   v="false"
@@ -489,21 +490,39 @@ server_update() {
 
 server_update_check() {
   # Return
-  #   0 if online version differs from installed minecraft_server.jar
+  #   0 if online version based on config differs from installed minecraft_server.jar
   #   1 if theres no difference between online and local version numbers
   #   2 if an error occured
   
   local json_regex line
   
   if [ ! $version = "release" ] && [ ! $version = "snapshot" ]; then
-    printf "   %s\n" "Error: version parameter in config must be set to either \"release\" or \"snapshot\""
-    return 2
+    if online_version_exists "$version"; then
+      if server_version; then
+        if [[ "$version_current" = "$version" ]]; then
+          return 1
+        else
+          if online_version_downloadable "$version"; then
+            version_online="$version"
+            return 0
+          else
+            printf "   %s\n" "Specified version: $version is not available for download."
+            return 2
+          fi
+        fi
+      else
+        return 2
+      fi
+    else
+      printf "   %s\n" "Error: version parameter in config must be set to either \"release\", \"snapshot\" or an available version"
+      return 2
+    fi
   fi
   
   json_regex="\"($version)\": \"(.*)\""
   
   as_user "mkdir -p $resources"
-  as_user "wget -qN -P $resources $versions_json"
+  as_user "wget -qN -P $resources $versions_json" || return 2
   
   while read line; do
     if [[ $line =~ $json_regex ]]; then
@@ -562,6 +581,54 @@ server_version_minimum() {
   else
     return 1
   fi
+}
+
+online_version_downloadable() {
+  # Usage
+  #   online_version_downloadable <x.x.x>
+  # Return
+  #   0 if server version x.x.x is downloadable
+  #   1 if server version x.x.x is not downloadable or check failed
+  local statuscode server_url
+  
+  server_url="https://s3.amazonaws.com/Minecraft.Download/versions/$1/minecraft_server.$1.jar"
+  statuscode=$(wget --spider -S "$server_url" 2>&1 | grep "HTTP/" | awk '{print $2}')
+  
+  if [ $statuscode = "200" ]; then
+    return 0
+  else
+    return 1
+  fi
+  
+}
+
+online_version_exists() {
+  # Usage
+  #   online_version_exists <x.x.x>
+  # Return
+  #   0 if server version x.x.x exists
+  #   1 if server version x.x.x does not exists or check failed
+  
+  local id_regex line version_exists
+  
+  as_user "mkdir -p $resources"
+  as_user "wget -qN -P $resources $versions_json" || return 1
+  
+  id_regex="\"id\": \"($1)\""
+  
+  while read line; do
+    if [[ $line =~ $id_regex ]]; then
+      version_exists="${BASH_REMATCH[1]}"
+      break
+    fi
+  done <"$resources/versions.json"
+  
+  if [ ! -z $version_exists ]; then
+    return 0
+  else
+    return 1
+  fi
+
 }
 
 case "$1" in
@@ -675,16 +742,24 @@ case "$1" in
     server_update_check
     case "$?" in
       0)
-        log_daemon_msg "New $version available: $version_online (currently running $version_current)"
+        if [ "$(version_timestamp \"$version\")" -gt "$(version_timestamp \"$version_current\")" ]; then
+          log_daemon_msg "New $version available: $version_online (currently running $version_current)"
+        else
+          log_daemon_msg "$version available for download (currently running $version_current)"
+        fi
       ;;
       1)
-        log_daemon_msg "$desc is running latest $version ($version_current)"
+        if [ $version = "release" ] or [ $version = "snapshot" ]; then
+          log_daemon_msg "$desc is running latest $version ($version_current)"
+        else
+          log_daemon_msg "$desc is running specified version in configuration ($version_current)"
+        fi
       ;;
       2) log_end_msg 1; exit 1 ;;
     esac
   ;;
   update)
-    log_daemon_msg "Checking for new version tagged \"$version\""
+    log_daemon_msg "Checking for version tagged \"$version\""
     server_update_check
     case "$?" in
       0)
@@ -733,7 +808,7 @@ case "$1" in
             server_update "$version_online"
             case "$?" in
               0)
-                log_daemon_msg "Successfully updated server to $version: $version_online"
+                log_daemon_msg "Successfully updated server to $version_online"
                 log_end_msg 0
               ;;
               1) log_end_msg 1; exit 1 ;;
@@ -742,7 +817,11 @@ case "$1" in
         esac
       ;;
       1)
-        log_daemon_msg "$desc is already running latest $version ($version_current)"
+        if [ $version = "release" ] or [ $version = "snapshot" ]; then
+          log_daemon_msg "$desc is running latest $version ($version_current)"
+        else
+          log_daemon_msg "$desc is running specified version in configuration ($version_current)"
+        fi
       ;;
       2)
         log_end_msg 1
