init config + partial log bug fix
Issuing config <setting> <value> now updates configuration file. Server
output older than one day gets flushed since last entry can be ”newer”
on the previous day (eg. 18:03) than current day (that can be for
example 16:03).

diff --git a/minecraft b/minecraft
--- a/minecraft
+++ b/minecraft
@@ -40,7 +40,7 @@ fi
 
 # Variables
 resource_versions="$resources/versions"
-log_start_regex="Starting minecraft server version (.*)"
+log_start_regex="minecraft server version (.*)"
 server_properties_file="$server/server.properties"
 server_properties_regex="^([a-z-]*)=(.*)"
 versions_json=http://s3.amazonaws.com/Minecraft.Download/versions/versions.json
@@ -103,6 +103,22 @@ version_timestamp() {
   
   printf "%s" $(date -d "$releasetime" +%s)
   
+  return 0
+}
+
+init_config() {
+  # Usage
+  #   init_config <variable> <setting>
+  # Return
+  #   0 if command was sent successfully
+  #   1 if command was unknown or failed
+  
+  setting=$1
+  value=$2
+  
+  updated="${setting}=\"${value}\""
+  
+  sudo sed -i 's#^'"$setting"'.*#'"$updated"'#' /etc/default/$name
   return 0
 }
 
@@ -169,6 +185,21 @@ server_command() {
   )
 
   timestamp=$(date +%s)
+  log_modified=$(stat -c %Y $log)
+  
+#   timestamp_date=$(date +%F)
+#   log_modified_date=$(date -d @$log_modified +%F)
+#   
+#   echo "Timestamp date: $timestamp_date, Log modified date: $log_modified_date"
+  
+#   if [ ! $timestamp_date = $log_modified_date ]; then
+#     echo "Flush file."
+#     if server_version; then
+#       echo "[$(date +%T)] [Init script/INFO]: Current minecraft server version $version_current" > $log
+#     else
+#       > $log
+#     fi
+#   fi
   
   as_user "printf \"%s\n\"  \"$1\" > $fifo"
   
@@ -176,6 +207,8 @@ server_command() {
     tail -f $log | while read log_line; do
   
       server_log "$log_line"
+      
+#       echo "Logline: $log_line_timestamp, Timestamp: $timestamp"
       
       # If log timestamp is less than command timestamp, skip iteration
       [[ $log_line_timestamp -lt $timestamp ]] && continue
@@ -736,6 +769,20 @@ case "$1" in
       1) log_daemon_msg "$desc is not running" ;;
     esac
   ;;
+  config)
+    server_is_running
+    case "$?" in
+      0)
+        log_daemon_msg "$desc is running, restart server for changes to take effect."
+        init_config "$2" "$3"
+        case "$?" in
+          0) log_end_msg 0 ;;
+          1) log_end_msg 1; exit 1 ;;
+        esac
+      ;;
+      1) init_config "$2" "$3" ;;
+    esac
+  ;;
   check-update)
     server_update_check
     case "$?" in
@@ -849,7 +896,7 @@ case "$1" in
   ;;
 # Catch all
   help|*)
-    printf "%s\n" "Usage: service $name {start|stop|status|restart|reload|command|check-update|update|version|help}" >&2
+    printf "%s\n" "Usage: service $name {start|stop|status|restart|reload|command|config|check-update|update|version|help}" >&2
     exit 3
   ;;
 esac
