added functionality and bug fixes for properties

diff --git a/minecraft b/minecraft
--- a/minecraft
+++ b/minecraft
@@ -379,7 +379,7 @@ server_properties() {
     
     server_setting["$setting"]="$value"
 
-  done <$server_properties_file
+  done <$server_properties_file || return 1
   
   return 0
 }
@@ -389,12 +389,19 @@ server_properties_update() {
   #   server_properties_update <setting> <value>
   # Return
   #   0 if command was sent successfully
+  #   1 if specified setting does not exist
 
   local setting=$1 value=$2 updated
   
   # TODO: Add check, eg. if "#" or something fishy
   
   updated="${setting}=${value}"
+  
+  server_properties
+  if [[ ! ${server_setting[$setting]} ]]; then
+    printf "   %s\n" "Error: The setting $setting does not exist in $server_properties_file";
+    return 1
+  fi
   
   sed -i 's#^'"$setting"'.*#'"$updated"'#' $server_properties_file
   return 0
@@ -822,13 +829,26 @@ case "$1" in
     esac
   ;;
   properties)
+    if [ ! $2 ]; then
+      log_daemon_msg "No setting specified. Usage: service minecraft properties <setting> [new value]"
+      exit 0
+    elif [ ! $3 ]; then
+      server_properties
+      log_daemon_msg "Currect setting for $2:"
+      if [[ ! ${server_setting[$2]} ]]; then
+        log_end_msg 1
+        exit 1
+      fi
+      printf "   %s\n" $2=${server_setting[$2]}
+      exit 0
+    fi
     server_is_running
     case "$?" in
       0)
-        log_daemon_msg "$desc is running, restart server for changes to take effect."
+        log_daemon_msg "Updating $desc properties."
         server_properties_update "$2" "$3"
         case "$?" in
-          0) log_end_msg 0 ;;
+          0) printf "   %s\n" "Note: $desc is running, restart server for changes to take effect."; log_end_msg 0 ;;
           1) log_end_msg 1; exit 1 ;;
         esac
       ;;
